Vagrant.configure("2") do |config|
    config.vm.define "hkovacS" do |hkovacS|
        hkovacS.vm.box = "debian/bookworm64"
        hkovacS.vm.network "private_network", ip: "192.168.56.110"
        hkovacS.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        hkovacS.vm.hostname = "hkovacS"
        hkovacS.vm.synced_folder "./confs", "/confs"
        hkovacS.vm.provision "shell", inline: <<-SHELL
            echo "Start provisioning hkovacS"
            sudo apt-get update
            sudo apt-get install curl net-tools -y
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" sh -
            export IP=192.168.56.110
            kubectl apply -f /confs/install.yaml

        SHELL
    end
end
