Vagrant.configure("2") do |config|
    config.vm.define "hkovacS" do |hkovacS|
        hkovacS.vm.box = "debian/bookworm64"
        hkovacS.vm.network "private_network", ip: "192.168.56.110"
        hkovacS.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        hkovacS.vm.hostname = "hkovacS"
        hkovacS.vm.synced_folder "./confs", "/token"
        hkovacS.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install curl net-tools -y
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" sh -
            sudo cp /var/lib/rancher/k3s/server/node-token /token/node-token
            sudo chmod 644 /token/node-token
        SHELL
    end
    config.vm.define "hkovacSW" do |hkovacSW|
        hkovacSW.vm.box = "debian/bookworm64"
        hkovacSW.vm.network "private_network", ip: "192.168.56.111"
        hkovacSW.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        hkovacSW.vm.hostname = "hkovacSW"
        hkovacSW.vm.synced_folder "./confs", "/token"
        hkovacSW.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install curl -y
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=`cat /token/node-token` sh -

            echo "hostname:"
            hostname
        SHELL
    end
end
